FROM @make:docker_base_image@

STOPSIGNAL SIGTERM

#^
#^-- specified by the base image
#
#v-- specified by the current image
#v

ENV     buildroot_user_name=developer
ENV     buildroot_group_name=developer
ENV     buildroot_account_description="Developer account"

#

ENV     buildroot_docker_image_setup_root=/v/setup.buildroot
VOLUME  [ "${buildroot_docker_image_setup_root}" ]

ENV     buildroot_user_home=/home/${buildroot_user_name}

ENV     buildroot_user_home_ref=/v/home.ref
VOLUME  [ "${buildroot_user_home_ref}" ]

ENV     buildroot_user_sandbox_root=/v/sandbox
VOLUME  [ "${buildroot_user_sandbox_root}" ]

ENV     buildroot_install_might_fail_p=t

##
## ensure everything is installed
##

USER    root
WORKDIR "${buildroot_docker_image_setup_root}"

COPY    support/container/software/provision.prolog.sh support/container/software/

COPY    support/container/software/packages.*.txt support/container/software/

COPY    support/container/software/provision.01.sh support/container/software/
RUN     sh support/container/software/provision.01.sh

COPY    artifacts/ artifacts/

COPY    support/container/software/provision.02.sh support/container/software/
RUN     sh support/container/software/provision.02.sh

COPY    support/container/software/etc/ support/container/software/etc/

##
## ensure members of group sudo don't need to authenticate further
## 

USER    root
WORKDIR "${buildroot_docker_image_setup_root}"

RUN     ! [ -d /etc/sudoers.d ] || \
	for f1 in /etc/sudoers.d/group-sudo-no-password-needed ; do \
        \
		echo '%sudo ALL = NOPASSWD: ALL' > "$f1" ; \
		chmod 0440 "$f1" ; \
	done

##
## ensure the buildroot user exists
##

USER    root
WORKDIR "${buildroot_docker_image_setup_root}"

RUN     addgroup "${buildroot_group_name}"

RUN     adduser \
		--shell    "/bin/bash" \
		--home     "${buildroot_user_home}" \
		--ingroup  "${buildroot_group_name}" \
		--gecos    "${buildroot_account_description}" \
		--disabled-password \
		"${buildroot_user_name}"

RUN     adduser "${buildroot_user_name}" root
RUN     adduser "${buildroot_user_name}" sudo

COPY    support/container/home-skeleton/ "${buildroot_user_home}"/

##
## ensure all remaining setup files are in place
## 

USER    root
WORKDIR "${buildroot_docker_image_setup_root}"

COPY    ./ ./

##
## establish entry point
##

USER    root
WORKDIR "${buildroot_docker_image_setup_root}"

COPY    start.sh ./

ENTRYPOINT [ "./start.sh" ]

##
